package arif.dxball;

public enum Status {
	BAR_TOP,BAR_CORNER,BRICK_TOP,BRICK_BOTTOM,BRICK_LEFT,BRICK_RIGHT,
	NONE,
	CORNER,TOP,SIDE,
	BAR_TOP_LEFT,BAR_TOP_MIDDLE,BAR_TOP_RIGHT,
	INSIDE_TOP,INSIDE_SIDE,INSIDE_CORNER,
}
